### ISSUE TITLE
Csg does not build with gromacs 3.3 under Ubuntu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#106]
```
What steps will reproduce the problem?
1.I run the ./build.sh command and recieve several errors


2.michael@michael-laptop:~/Desktop/votca-csg-1.2/src$ ./build.sh 
This is VOTCA build.sh, version 1.6.1
prefix is '/home/michael/votca'
Using 3 jobs for make
Working on tools
Source dir (tools) is already there - skipping checkout
cmake -DCMAKE_INSTALL_PREFIX=/home/michael/votca  .
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: 
/home/michael/Desktop/votca-csg-1.2/src/tools
buidling tools
[  9%] [  9%] Building CXX object CMakeFiles/csg_dump.dir/csg_dump.o
Building CXX object CMakeFiles/csg_density.dir/csg_density.o
[  9%] Building CXX object CMakeFiles/csg_fmatch.dir/csg_fmatch.o
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:19:38: error: 
votca/csg/csgapplication.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:23:42: error: 
boost/numeric/ublas/vector.hpp: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:24:49: error: 
boost/numeric/ublas/matrix_sparse.hpp: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:25:42: error: 
boost/numeric/ublas/matrix.hpp: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:26:37: error: 
votca/tools/cubicspline.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:27:34: error: 
votca/csg/nblistgrid.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:28:32: error: 
votca/csg/beadlist.h: No such file or directory
In file included from 
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:29:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:21:34: error: 
votca/tools/property.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:26:38: error: 
votca/csg/csgapplication.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:27:40: error: 
votca/csg/trajectoryreader.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:30:31: error: 
votca/tools/table.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:31:32: error: 
votca/tools/linalg.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:22: error: 
‘votca’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:22: error: ‘csg’ 
is not a namespace-name
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:22: error: expected 
namespace-name before ‘;’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:26: error: expected 
class-name before ‘{’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:27: error: 
‘string’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:28: error: 
‘ostream’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:36: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:36: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc: In member function 
‘void CsgDumpApp::HelpText(int&)’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:29: error: invalid 
operands of types ‘int’ and ‘const char [76]’ to binary ‘operator<<’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc: In member function 
‘void CsgDumpApp::Initialize()’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:31: error: 
‘CsgApplication’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:32: error: 
‘AddProgramOptions’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc: In function ‘int 
main(int, char**)’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:46: error: ‘class 
CsgDumpApp’ has no member named ‘Exec’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc: At global scope:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: ‘bool 
CsgDumpApp::EvaluateTopology’ is not a static member of ‘class CsgDumpApp’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: ‘top’ 
was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: 
‘top_ref’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:49: error: 
initializer expression list treated as compound expression
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_dump.cc:50: error: expected 
‘,’ or ‘;’ before ‘{’ token
make[2]: *** [CMakeFiles/csg_dump.dir/csg_dump.o] Error 1
make[1]: *** [CMakeFiles/csg_dump.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:19:38: error: 
votca/tools/histogramnew.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:20:35: error: 
votca/tools/tokenizer.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:21:38: error: 
votca/csg/csgapplication.h: No such file or directory
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:24: error: 
‘votca’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:24: error: 
‘csg’ is not a namespace-name
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:24: error: 
expected namespace-name before ‘;’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:25: error: 
‘votca’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:25: error: 
‘tools’ is not a namespace-name
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:25: error: 
expected namespace-name before ‘;’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:30: error: 
expected class-name before ‘{’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:31: error: 
‘string’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:32: error: 
‘ostream’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:46: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:46: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:47: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:47: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:57: error: 
‘string’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:58: error: 
‘HistogramNew’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:63: error: 
‘vec’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:64: error: 
‘vec’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:65: error: 
‘string’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:66: error: 
‘string’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc: In member 
function ‘void CsgDensityApp::HelpText(int&)’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:33: error: invalid 
operands of types ‘int’ and ‘const char [105]’ to binary 
‘operator<<’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc: In member 
function ‘bool CsgDensityApp::EvaluateOptions()’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:50: error: 
‘CsgApplication’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:51: error: 
‘CheckRequired’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc: In function 
‘int main(int, char**)’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:73: error: 
‘class CsgDensityApp’ has no member named ‘Exec’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc: At global scope:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:76: error: 
variable or field ‘BeginEvaluate’ declared void
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:76: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:76: error: 
‘top’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:76: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_density.cc:76: error: 
‘top_atom’ was not declared in this scope
make[2]: *** [CMakeFiles/csg_density.dir/csg_density.o] Error 1
make[1]: *** [CMakeFiles/csg_density.dir/all] Error 2
In file included from 
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:29:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:29: error: 
‘votca’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:29: error: ‘csg’ 
is not a namespace-name
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:29: error: expected 
namespace-name before ‘;’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:45: error: expected 
class-name before ‘{’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:60: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:60: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:64: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:64: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:72: error: 
‘Property’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:84: error: 
‘CubicSpline’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:93: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:93: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:93: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:95: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:95: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:95: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:97: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:97: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:97: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:99: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:99: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:99: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:101: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:101: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:101: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:103: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:103: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:103: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:111: error: ISO C++ 
forbids declaration of ‘Property’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:111: error: expected 
‘;’ before ‘*’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:114: error: 
‘Property’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:116: error: ISO C++ 
forbids declaration of ‘list’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:116: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:118: error: ISO C++ 
forbids declaration of ‘list’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:118: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:120: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:120: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:122: error: 
‘SplineContainer’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:125: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:125: error: ISO C++ 
forbids declaration of ‘matrix’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:125: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:127: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:127: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:127: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:129: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:129: error: ISO C++ 
forbids declaration of ‘vector’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:129: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:132: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:132: error: ISO C++ 
forbids declaration of ‘matrix’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:132: error: expected 
‘;’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:157: error: ‘ub’ 
has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:157: error: expected 
‘,’ or ‘...’ before ‘<’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:159: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:161: error: 
‘Topology’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:167: error: 
‘Topology’ does not name a type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:168: error: ISO C++ 
forbids declaration of ‘TrajectoryReader’ with no type
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.h:168: error: expected 
‘;’ before ‘*’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc: In function ‘int 
main(int, char**)’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:36: error: ‘class 
CGForceMatching’ has no member named ‘Exec’
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc: In member function 
‘void CGForceMatching::Initialize()’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:42: error: 
‘CsgApplication’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:43: error: 
‘AddProgramOptions’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:44: error: 
‘boost’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:44: error: expected 
primary-expression before ‘>’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:44: error: expected 
primary-expression before ‘)’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:45: error: 
‘boost’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:45: error: expected 
primary-expression before ‘>’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:45: error: expected 
primary-expression before ‘)’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc: In member function 
‘bool CGForceMatching::EvaluateOptions()’:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:50: error: 
‘CsgApplication’ has not been declared
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:51: error: 
‘CheckRequired’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:53: error: 
‘OptionsMap’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:53: error: expected 
primary-expression before ‘>’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:53: error: expected 
primary-expression before ‘)’ token
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc: At global scope:
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:61: error: variable 
or field ‘BeginEvaluate’ declared void
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:61: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:61: error: 
‘top’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:61: error: 
‘Topology’ was not declared in this scope
/home/michael/Desktop/votca-csg-1.2/src/tools/csg_fmatch.cc:61: error: 
‘top_atom’ was not declared in this scope
make[2]: *** [CMakeFiles/csg_fmatch.dir/csg_fmatch.o] Error 1
make[1]: *** [CMakeFiles/csg_fmatch.dir/all] Error 2
make: *** [all] Error 2
michael@michael-laptop:~/Desktop/votca-csg-1.2/src$ 

3. I receive the same errors when I use the "./build.sh --prefix ${prefix} 
tools csg" line



Please provide any additional information below.

I have installed all of the dependencies.
```

Original issue reported on code.google.com by `manningm...@gmail.com` on 5 Jul 2011 at 2:50
