### ISSUE TITLE
lexical_cast.h does not build with gcc-4.2.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#73]
```
Please use labels and text to provide additional information.
e.cc -o libvotca_tools_la-correlate.o >/dev/null 2>&1
In file included from ../../include/property.h:23,
                 from ../../include/application.h:22,
                 from application.cc:19:
../../include/lexical_cast.h: In function 'Target 
votca::tools::lexical_cast(const Source&, const std::string&)':
../../include/lexical_cast.h:39: error: expected type-specifier
../../include/lexical_cast.h:39: error: expected unqualified-id before '&' token
../../include/lexical_cast.h:39: error: expected `)' before '&' token
../../include/lexical_cast.h:39: error: expected `{' before '&' token
../../include/lexical_cast.h:39: error: 'err' was not declared in this scope
../../include/lexical_cast.h:39: error: expected `;' before ')' token
make[4]: *** [libvotca_tools_la-application.lo] Error 1
make[4]: *** Waiting for unfinished jobs....

```

Original issue reported on code.google.com by `christop...@gmail.com` on 11 Feb 2011 at 2:23
